name: to
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  hive: ^2.0.2
  uuid: ^3.0.5
  hive_flutter: ^1.0.0
  flutter: 
    sdk: flutter
  path_provider: ^2.0.7

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

